apps/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('balanced_diets.urls')),
]

balanced_diet/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

balanced_diets/urls.py
from django.urls import path

from . import views
app_name = 'balanced_diets'
urlpatterns = [
    path('', views.index, name='index'),
    path('new_kcal/', views.new_kcal, name='new_kcal'),
    path('my_diet/', views.my_diet, name='my_diet'),
    path('edit_kcal/', views.edit_kcal, name='edit_kcal')
]

users/urls.py
from django.urls import path, include
from . import views
app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

balanced_diets/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Dish(models.Model):
    meals = [
        ('B', 'Завтрак'),
        ('L', 'Обед'),
        ('D', 'Ужин')
    ]
    name = models.CharField(max_length=50)
    kcal = models.DecimalField(max_digits=6, decimal_places=2)
    proteins = models.DecimalField(max_digits=6, decimal_places=2)
    fats = models.DecimalField(max_digits=6, decimal_places=2)
    carbs = models.DecimalField(max_digits=6, decimal_places=2)
    meal = models.CharField(max_length=15, choices=meals, default='')
    lactose = models.BooleanField()
    vegan = models.BooleanField()
    href = models.CharField(max_length=150, default='https://daily-menu.ru/dailymenu/recipes')


class Product(models.Model):
    name = models.CharField(max_length=50)

class Recipe(models.Model):
    id_dish = models.ForeignKey(Dish, on_delete=models.DO_NOTHING)
    id_product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)

class New_kcal(models.Model):
    genders = [
        ('M', 'Мужской'),
        ('F', 'Женский')
    ]
    activities = [
        ('1,2', 'Сидячий образ жизни.'),
        ('1,375', 'До трех малоинтенсивных тренировок в неделю.'),
        ('1,55', 'Тренировки три-четыре раза в неделю, тренировки интенсивные, но не тяжелые.'),
        ('1,7', 'Ежедневные занятия спортом или ежедневная работа, связанная с большим количеством перемещений и ручного труда.'),
        ('1,9', 'Экстремальная активность. Профессиональный спортсмен или работа с тяжестями и т.д.')
    ]
    name = models.CharField(max_length=150)
    gender = models.CharField(max_length=10, choices=genders, default='')
    weight = models.IntegerField()
    height = models.IntegerField()
    age = models.IntegerField()
    activity = models.CharField(max_length=50, choices=activities, default='')
    lactose = models.BooleanField(default=False)
    vegan = models.BooleanField(default=False)
    diabetes = models.BooleanField(default=False)

    def get_kcal(self):
        if self.gender == 'M':
            kcal_value = (10 * float(self.weight) + 6.25 * float(self.height) - 5 * float(self.age) + 5) * float(self.activity.replace(',', '.'))
        elif self.gender == 'F':
            kcal_value = (10 * float(self.weight) + 6.25 * float(self.height) - 5 * float(self.age) - 161) * float(self.activity.replace(',', '.'))
        belki = kcal_value * 0.3 / 4
        zhiri = kcal_value * 0.3 / 9
        uglevodi = kcal_value * 0.4 / 4
        return kcal_value, belki, zhiri, uglevodi


class exclusion_product(models.Model):
    id_user = models.ForeignKey(New_kcal, on_delete=models.DO_NOTHING)
    id_product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)

balanced_diets/forms.py
from django import forms
from .models import New_kcal


class KcalForm(forms.ModelForm):
    class Meta:
        model = New_kcal
        fields = ['gender','name','weight','height','age','activity','lactose','vegan']

balanced_diets/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
# Create your views here.
from django.http import HttpResponseRedirect, HttpResponseNotFound
from .models import New_kcal
from .forms import KcalForm


def index(request):
    kcal = New_kcal.objects.all()
    for i in kcal:
        if request.user.username == i.name:
            return render(request, 'balanced_diets/index.html', {"name": i.name})
    else:
        return render(request, 'balanced_diets/index.html')


def new_kcal(request):
    if request.method != 'POST':
        form = KcalForm()
    else:
        form = KcalForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('balanced_diets:my_diet')

    context = {'form': form}
    return render(request, 'balanced_diets/new_kcal.html', context)


def edit_kcal(request):
    kcal_id = request.user.username
    kcal = New_kcal.objects.get(name=kcal_id)
    if request.method != 'POST':
        form = KcalForm(instance=kcal)
    else:
        form = KcalForm(instance=kcal, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('balanced_diets:my_diet')
    context = {'kcal': kcal, 'form': form}
    return render(request, 'balanced_diets/edit_kcal.html', context)


@login_required
def my_diet(request):
    kcal = New_kcal.objects.all()
    for i in kcal:
        if request.user.username == i.name:
            kbzu = New_kcal.get_kcal(i)
            context = {
                "kal": kbzu[0],
                "belki": kbzu[1],
                "zhiri": kbzu[2],
                "ugl": kbzu[3],
            }
            return render(request, 'balanced_diets/my_diet.html', context)


    else:
        return render(request, 'balanced_diets/my_diet.html')

balanced_diets/templates/balanced_diets/base.html
<!doctype html>
<html lang="en" style="height: 100%">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body style=" height: 100%">
<nav class="navbar navbar-expand-lg navbar-dark bg-success"  >
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'balanced_diets:index' %}">bd</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'balanced_diets:index' %}">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Инструкция</a>
        </li>
          {% if user.is_authenticated %}
          <li class="nav-item">

                <a class="nav-link" href="{% url 'balanced_diets:my_diet' %}">Моя диета</a>
              {% else %}
                <a class="nav-link" href="{% url 'users:login' %}">Войти</a>

        </li>
          <li class="nav_item">
                <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
          </li>

          {% endif %}
          {% if user.is_authenticated %}
          <li class="nav_item">
                <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
          </li>
          {% endif %}
      </ul>
    </div>
  </div>
</nav>
    {% block content %}{% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

balanced_diets/templates/balanced_diets/edit_kcal.html
{% extends "balanced_diets/base.html" %}
{% block content %}
<div class="container text-center rounded" style=" max-width: 300px; display: flex; justify-content: center; align-items: center; height: 100%; ">
    <form action="{% url 'balanced_diets:edit_kcal'%}" method='post'>
        {% csrf_token %}

        <div class="input-group mb-3 mt-3">
            <label for="id_gender" class="input-group-text">Gender&nbsp&nbsp</label>
            <select class="form-select" name="gender" value="{{ kcal.gender }}" id="id_gender">
            <option value="M" {% if kcal.gender == 'M' %} selected {% endif %} >Мужской</option>
            <option value="F" {% if kcal.gender == 'F' %} selected {% endif %}>Женский</option>
            </select>
        </div>

        <div class="input-group mb-3">
            <label for="id_name" class="input-group-text">Name&nbsp&nbsp&nbsp&nbsp</label>
            <input type="text" name="name" class="form-control text-center" value="{{ user.username }}" id="id_name" readonly>
        </div>

        <div class="input-group mb-3">
            <label for="id_weight" class="input-group-text">Weight&nbsp&nbsp</label>
            <input type="number" name="weight" class="form-control text-center" value="{{ kcal.weight }}" id="id_weight">
        </div>

        <div class="input-group mb-3">
            <label for="id_height" class="input-group-text">Height&nbsp&nbsp</label>
            <input type="number" name="height" class="form-control text-center" value="{{ kcal.height }}" id="id_height">
        </div>

        <div class="input-group mb-3">
            <label for="id_age" class="input-group-text">Age&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</label>
            <input type="number" name="age" class="form-control text-center" value="{{ kcal.age }}" id="id_age">
        </div>

        <div class="input-group mb-3">
            <label for="id_activity" class="input-group-text">Activity</label>
            <select class="form-select" name="activity"  id="id_activity" >
            <option value="1,2" {% if kcal.activity == '1,2' %} selected {% endif %}>Сидячий образ жизни.</option>
            <option value="1,375" {% if kcal.activity == '1,375' %} selected {% endif %}>До трех малоинтенсивных тренировок в неделю.</option>
            <option value="1,55" {% if kcal.activity == '1,55'%} selected {% endif %}>Тренировки три-четыре раза в неделю, тренировки интенсивные, но не тяжелые.</option>
            <option value="1,7" {% if kcal.activity == '1,7'%} selected {% endif %}>Ежедневные занятия спортом или ежедневная работа, связанная с большим количеством перемещений и ручного труда.</option>
            <option value="1,9" {% if kcal.activity == '1,9'%} selected {% endif %}>Экстремальная активность. Профессиональный спортсмен или работа с тяжестями и т.д.</option>

</select>
        </div>

        <div class="mb-3">
            <label for="id_lactose" class="form-check-label">Lactose</label>
            <input class="form-check-input" type="checkbox" name="lactose" class="form-control text-center" id="id_lactose"
            {% if kcal.lactose %} checked {% endif %}>
        </div>
        <div class="mb-3">

            <label for="id_vegan" class="form-check-label">Vegan</label>
            <input class="form-check-input" type="checkbox" name="vegan" class="form-control text-center" id="id_vegan"
            {% if kcal.vegan %} checked {% endif %}>


        </div>



        <button type="submit" class="btn btn-dark mb-3"  >Изменить</button>
        <input type="hidden" name="next" value="{% url 'balanced_diets:my_diet' %}" />

    </form>
    </div>




{% endblock content %}

balanced_diets/templates/balanced_diets/index.html
{% extends "balanced_diets/base.html" %}
{% block content %}
{% if user.is_authenticated %}
<div class="d-grid gap-2 col-6 mx-auto" style="position: absolute;top: 50%;left: 50%;margin-right: -50%;transform: translate(-50%, -50%)">

    {% if name == user.Username %}
    <a class="btn btn-dark"  role="button" href="{% url 'balanced_diets:new_kcal' %}">Рассчитать КБЖУ</a>
    <a class="btn btn-dark"  type="button">Составить меню</a>

    {% else %}
    <a class="btn btn-dark"  type="button">Составить меню</a>
    {% endif %}

 </div>
{% else %}
<div class="d-grid gap-2 col-6 mx-auto" style="position: absolute;top: 50%;left: 50%;margin-right: -50%;transform: translate(-50%, -50%)">
<h1>You must be logged in.</h1>
</div>
{% endif %}
{% endblock content %}

balanced_diets/templates/balanced_diets/my_diet.html
{% extends "balanced_diets/base.html" %}
{% block content %}
    {% if kal is not None %}
        <div style="margin-left: 10%">
         <h1>
        <ul class="list-group">Суточная норма пользователя {{user.username}}:
            <li>Калории: {{kal}}</li>
            <li>Белки: {{belki}}</li>
            <li>Жиры: {{zhiri}}</li>
            <li>Углеводы: {{ugl}}</li>
        </ul>
             </h1>
              <a class="btn btn-dark"  role="button" href="{% url 'balanced_diets:edit_kcal' %}">Изменить свои данные</a>
        </div>




    {% else %}
        <h1> Подсчитайте калории на главной странице!</h1>
    {% endif %}
{% endblock content %}

balanced_diets/templates/balanced_diets/new_kcal.html
{% extends "balanced_diets/base.html" %}
{% block content %}
<div class="container text-center rounded" style=" max-width: 300px; display: flex; justify-content: center; align-items: center; height: 100%; ">
    <form action="{% url 'balanced_diets:new_kcal' %}" method='post'>
        {% csrf_token %}

        <div class="input-group mb-3 mt-3">
            <label for="id_gender" class="input-group-text">Gender&nbsp&nbsp</label>
            <select class="form-select" name="gender" id="id_gender">
            <option value="M">Мужской</option>
            <option value="F">Женский</option>
            </select>
        </div>

        <div class="input-group mb-3">
            <label for="id_name" class="input-group-text">Name&nbsp&nbsp&nbsp&nbsp</label>
            <input type="text" name="name" class="form-control text-center" value="{{ user.username }}" id="id_name" readonly>
        </div>

        <div class="input-group mb-3">
            <label for="id_weight" class="input-group-text">Weight&nbsp&nbsp</label>
            <input type="number" name="weight" class="form-control text-center" id="id_weight">
        </div>

        <div class="input-group mb-3">
            <label for="id_height" class="input-group-text">Height&nbsp&nbsp</label>
            <input type="number" name="height" class="form-control text-center" id="id_height">
        </div>

        <div class="input-group mb-3">
            <label for="id_age" class="input-group-text">Age&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</label>
            <input type="number" name="age" class="form-control text-center" id="id_age">
        </div>

        <div class="input-group mb-3">
            <label for="id_activity" class="input-group-text">Activity</label>
            <select class="form-select" name="activity" id="id_activity">
            <option value="1,2">Сидячий образ жизни.</option>
            <option value="1,375">До трех малоинтенсивных тренировок в неделю.</option>
            <option value="1,55">Тренировки три-четыре раза в неделю, тренировки интенсивные, но не тяжелые.</option>
            <option value="1,7">Ежедневные занятия спортом или ежедневная работа, связанная с большим количеством перемещений и ручного труда.</option>
            <option value="1,9">Экстремальная активность. Профессиональный спортсмен или работа с тяжестями и т.д.</option>

</select>
        </div>

        <div class="mb-3">
            <label for="id_lactose" class="form-check-label">Lactose</label>
            <input class="form-check-input" type="checkbox" name="lactose" class="form-control text-center" id="id_lactose">
        <div class="mb-3">

            <label for="id_vegan" class="form-check-label">Vegan</label>
            <input class="form-check-input" type="checkbox" name="vegan" class="form-control text-center" id="id_vegan">
        </div>
        </div>



        <button type="submit" class="btn btn-dark mb-3"  >Рассчитать КБЖУ</button>
        <input type="hidden" name="next" value="{% url 'balanced_diets:my_diet' %}" />

    </form>
    </div>




{% endblock content %}